<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="gripper" params="prefix parent side damping friction grpc_multiplexer_url gripper_grasping_finger_id gripper_action_finger_id">

  <xacro:include filename="$(find xprize_reachy_description)/ros2_control/gripper.ros2_control.xacro"/>

  <xacro:property name="gripper_length" value="0.12"/>
  <xacro:property name="gripper_radius" value="0.03"/>
  <xacro:property name="gripper_mass" value="0.25"/>

  <xacro:if value="${side == 'left'}">
    <xacro:property name="reflect" value="-1"/>
    <xacro:property name="min_grasping_finger" value="-2.094"/>
    <xacro:property name="max_grasping_finger" value="0.785"/>
    <xacro:property name="min_action_finger" value="-1.745"/>
    <xacro:property name="max_action_finger" value="0.0"/>
  </xacro:if>
  <xacro:if value="${side == 'right'}">
    <xacro:property name="reflect" value="1"/>
    <xacro:property name="min_grasping_finger" value="-0.785"/>
    <xacro:property name="max_grasping_finger" value="2.094"/>
    <xacro:property name="min_action_finger" value="0.0"/>
    <xacro:property name="max_action_finger" value="1.745"/>
  </xacro:if>

  <xacro:property name="p" value="${prefix}_gripper"/>

    <!--
      Gripper

    link                      (joint)

    ${parent}                  (${p}_palm) fixed
      ${p}_palm_link           (${p}_thumb) fixed
        ${p}_thumb_link        
                               (${p}_dummy_index) fixed
        ${p}_index_dummy_link  (${p}_grasping_finger) REVOLUTE
          ${p}_index_link
                               (${p}_action_finger) REVOLUTE
          ${p}_action_link
    -->

  <link name="${p}_palm_link">
    <collision>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} ${gripper_radius*2} ${gripper_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} ${gripper_radius*2} ${gripper_length/2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <xacro:inertial_cuboid mass="${gripper_mass*0.85}" xyz="0 0 ${gripper_length/4}"  rpy="0 0 0" x_length="${gripper_radius}" y_length="${gripper_radius*2}" z_length="${gripper_length/2}"/>
  </link>

  <joint name="${p}_palm" type="fixed">
    <origin xyz="0 0 0" rpy="0.0 0 -0.5"/>
    <parent link="${parent}"/>
    <child link="${p}_palm_link"/>
  </joint>

  <link name="${p}_thumb_link">
    <collision>
      <origin xyz="0 ${(-gripper_radius+0.005)*reflect} ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} 0.01 ${gripper_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${(-gripper_radius+0.005)*reflect} ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} 0.01 ${gripper_length/2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <xacro:inertial_cuboid mass="${gripper_mass*0.05}" xyz="0 ${(-gripper_radius+0.005)*reflect} ${gripper_length/4}"  rpy="0 0 0" x_length="${gripper_radius}" y_length="0.01" z_length="${gripper_length/2}"/>
  </link>

  <joint name="${p}_thumb" type="fixed">
    <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
    <parent link="${p}_palm_link"/>
    <child link="${p}_thumb_link"/>
  </joint>

  <link name="${p}_index_dummy_link">
    <visual>
      <origin xyz="0 ${reflect*gripper_radius} ${gripper_length/4} " rpy="0 1.5 0"/>
      <geometry>
        <cylinder length="${gripper_radius}" radius="0.01"/>
      </geometry>
      <material name="red"/>
    </visual>
    <xacro:inertial_cuboid mass="${gripper_mass*0.1}" xyz="0 ${reflect*gripper_radius} ${gripper_length/4}"  rpy="0 0 0" x_length="${gripper_radius}" y_length="0.01" z_length="${gripper_length/2}"/>
  </link>

  <joint name="${p}_dummy_index" type="fixed">
    <origin xyz="0 0 ${gripper_length/4}" rpy="0 0 0"/>
    <parent link="${p}_palm_link"/>
    <child link="${p}_index_dummy_link"/>
  </joint>

  <link name="${p}_index_link">
    <collision>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} 0.01 ${gripper_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} 0.01 ${gripper_length/2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <xacro:inertial_cuboid mass="${gripper_mass*0.1}" xyz="0 ${gripper_radius} ${gripper_length/4}"  rpy="0 0 0" x_length="${gripper_radius}" y_length="0.01" z_length="${gripper_length/2}"/>
  </link>

  <joint name="${p}_grasping_finger" type="revolute">
    <origin xyz="0 ${reflect*gripper_radius} ${gripper_length/2}" rpy="0 0 0"/>
    <parent link="${p}_palm_link"/>
    <child link="${p}_index_link"/>
    <axis xyz="1 0 0"/>
    <limit lower="${min_grasping_finger}" upper="${max_grasping_finger}" effort="1000.0" velocity="0.0"/>
    <dynamics damping="${damping}" friction="${friction}"/>
  </joint>

  <link name="${p}_action_link">
    <collision>
      <origin xyz="${gripper_radius} 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius/2} 0.01 ${gripper_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${gripper_radius} 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius/2} 0.01 ${gripper_length/2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <xacro:inertial_cuboid mass="${gripper_mass*0.1}" xyz="0 ${gripper_radius} ${gripper_length/4}"  rpy="0 0 0" x_length="${gripper_radius}" y_length="0.01" z_length="${gripper_length/2}"/>
  </link>

  <joint name="${p}_action_finger" type="revolute">
    <origin xyz="0 ${reflect*gripper_radius} ${gripper_length/2}" rpy="0 0 0"/>
    <parent link="${p}_palm_link"/>
    <child link="${p}_action_link"/>
    <axis xyz="1 0 0"/>
    <limit lower="${min_action_finger}" upper="${max_action_finger}" effort="1000.0" velocity="0.0"/>
    <dynamics damping="${damping}" friction="${friction}"/>
  </joint>

  <xacro:gripper_grpc_control
    name="${p}"
    grpc_multiplexer_url="${grpc_multiplexer_url}" 
    gripper_grasping_finger_id="${gripper_grasping_finger_id}" 
    gripper_action_finger_id="${gripper_action_finger_id}"
    min_grasping_finger="${min_grasping_finger}"
    max_grasping_finger="${max_grasping_finger}"
    min_action_finger="${min_action_finger}"
    max_action_finger="${max_action_finger}"
  />

</xacro:macro>
</robot>
