<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find reachy_description)/urdf/inertial_primitives.urdf.xacro"/>
  <xacro:include filename="$(find reachy_description)/ros2_control/orbita.ros2_control.xacro"/>

  <xacro:macro name="orbita" params="name parent length radius mass xyz rpy damping friction orbita_serial_port orbita_id orbita_hardware_zero orbita_reduction">
    <!-- 54Â°?? -->
  <xacro:property name="orbita_alpha" value="0.9424777960769379"/>

    <material name="orbitayellow">
        <color rgba="0.8 0.8 0.0 1"/>
    </material>
    <material name="orbitagrey">
        <color rgba="0.8 0.8 0.8 1"/>
    </material>

    <!--
      Orbita

    link                      (joint)

    ${parent}                  (${name}_roll)
      ${name}_dummy_link1      (${name}_pitch)
        ${name}_dummy_link2    (${name}_yaw)
          ${name}_link         (${name}_ball_joint)
            ${name}_ball_link
    -->

    <link name="${name}_dummy_link1">
      <xacro:inertial_cuboid mass="${mass*0.01}" xyz="0 0 0"  rpy="0 0 0" x_length="${radius*2}" y_length="${radius*2}" z_length="${length}">
      </xacro:inertial_cuboid>
    </link>

    <link name="${name}_dummy_link2">
      <xacro:inertial_cuboid mass="${mass*0.01}" xyz="0 0 0"  rpy="0 0 0" x_length="${radius*2}" y_length="${radius*2}" z_length="${length}">
      </xacro:inertial_cuboid>
    </link>

    <link name="${name}_link">
      <visual>
      	<origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      	<geometry>
          <cylinder length="${length}" radius="${radius}"/>
      	</geometry>
      	<material name="orbitayellow"/>
      </visual>

      <collision>
      	<origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      	<geometry>
          <cylinder length="${length}" radius="${radius}"/>
      	</geometry>
      </collision>

      <xacro:inertial_cuboid mass="${mass*0.48}" xyz="0 0 ${-length/2}"  rpy="0 0 0" x_length="${radius*2}" y_length="${radius*2}" z_length="${length}">
      </xacro:inertial_cuboid>
    </link>

    <link name="${name}_ball_link">
      <visual>
      	<origin xyz="0 0 0" rpy="0 0 0"/>
      	<geometry>
          <sphere radius="${radius*1.2}"/>
      	</geometry>
      	<material name="orbitagrey"/> 
      </visual>
      <collision>
      	<origin xyz="0 0 0" rpy="0 0 0"/>
      	<geometry>
          <sphere radius="${radius*1.2}"/>
      	</geometry>
      </collision>
      <xacro:inertial_sphere mass="${mass*0.5}" diameter="${2*radius*1.2}"/>
    </link>

    <joint name="${name}_ball_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_ball_link"/>
    </joint>

    <joint name="${name}_roll" type="revolute">
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <parent link="${parent}"/>
      <child link="${name}_dummy_link1"/>
      <axis xyz="1 0 0"/>
      <limit lower="-0.35" upper="0.35" effort="1000.0" velocity="100.0"/>
      <dynamics damping="${damping}" friction="${friction}"/>
    </joint>

    <joint name="${name}_pitch" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_dummy_link1"/>
      <child link="${name}_dummy_link2"/>
      <axis xyz="0 1 0"/>
      <limit lower="-0.35" upper="0.35" effort="1000.0" velocity="100.0"/>
      <dynamics damping="${damping}" friction="${friction}"/>
    </joint>

    <joint name="${name}_yaw" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_dummy_link2"/>
      <child link="${name}_link"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="1000.0" velocity="100.0"/>
      <dynamics damping="${damping}" friction="${friction}"/>
    </joint>

    <xacro:orbita_control
      name="${name}"
      orbita_serial_port="${orbita_serial_port}" orbita_id="${orbita_id}"
      orbita_alpha="${orbita_alpha}" orbita_hardware_zero="${orbita_hardware_zero}" orbita_reduction="${orbita_reduction}"
    />

  </xacro:macro>
</robot>
