<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find reachy_description)/urdf/inertial_primitives.urdf.xacro"/>
  <xacro:include filename="$(find reachy_description)/ros2_control/orbita2dof.ros2_control.xacro"/>

  <xacro:macro name="joint2axis" params="joint">
    <xacro:if value="${joint == 'roll'}">
      <axis xyz="1 0 0"/>
    </xacro:if>
    <xacro:if value="${joint == 'pitch'}">
      <axis xyz="0 1 0"/>
    </xacro:if>
    <xacro:if value="${joint == 'yaw'}">
      <axis xyz="0 0 1"/>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="orbita2dof" params="name parent length radius mass xyz rpy damping friction joint1 joint2 joint1_min_angle joint1_max_angle joint2_min_angle joint2_max_angle port_a port_b id_a id_b offset_a offset_b ratio_a ratio_b pitch_inverted">

    <!--
      Orbita 2 dof

    link                      (joint)

    ${parent}                 (${name}_joint1)
      ${name}_dummy_link      (${name}_joint2)
        ${name}_link          (${name}_ball_joint)
          ${name}_ball_link
    -->

    <link name="${name}_dummy_link">
      <xacro:inertial_cuboid mass="${mass*0.01}" xyz="0 0 0"  rpy="0 0 0" x_length="${radius*2}" y_length="${radius*2}" z_length="${length}"/>
    </link>

    <joint name="${name}_${joint1}" type="revolute">
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <parent link="${parent}"/>
      <child link="${name}_dummy_link"/>
      <xacro:joint2axis joint="${joint1}"/>
      <limit lower="${joint1_min_angle}" upper="${joint1_max_angle}" effort="1000.0" velocity="100.0"/>
      <safety_controller k_velocity="500" k_position="500" soft_lower_limit="-3.1415" soft_upper_limit="3.1415" />
      <dynamics damping="${damping}" friction="${friction}"/>
    </joint>

    <link name="${name}_link">
      <collision>
      	<origin xyz="0 0 ${-length/2}" rpy="0 0 0"/>
      	<geometry>
          <cylinder length="${length}" radius="${radius}"/>
      	</geometry>
      </collision>
      <visual>
      	<origin xyz="0 0 ${-length/2}" rpy="0 0 0"/>
      	<geometry>
          <cylinder length="${length}" radius="${radius}"/>
      	</geometry>
      	<material name="yellow"/>
      </visual>

      <xacro:inertial_cuboid mass="${mass*0.49}" xyz="0 0 ${-length/2}"  rpy="0 0 0" x_length="${radius*2}" y_length="${radius*2}" z_length="${length}"/>
    </link>

    <joint name="${name}_${joint2}" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_dummy_link"/>
      <child link="${name}_link"/>
      <xacro:joint2axis joint="${joint2}"/>
      <limit lower="${joint2_min_angle}" upper="${joint2_max_angle}" effort="1000.0" velocity="100.0"/>
      <safety_controller k_velocity="500" k_position="500" soft_lower_limit="-3.1415" soft_upper_limit="3.1415" />
      <dynamics damping="${damping}" friction="${friction}"/>
    </joint>

    <gazebo reference="${name}_link">
      <material>Gazebo/Orange</material>
    </gazebo>

    <link name="${name}_ball_link">
      <visual>
      	<origin xyz="0 0 0" rpy="0 0 0"/>
      	<geometry>
          <sphere radius="${radius*1.2}"/>
      	</geometry>
      	<!-- <material name="grey"/> -->
      </visual>
      <collision>
      	<origin xyz="0 0 0" rpy="0 0 0"/>
      	<geometry>
          <sphere radius="${radius*1.2}"/>
      	</geometry>
      </collision>
      <xacro:inertial_sphere mass="${mass*0.5}" diameter="${2*radius*1.2}"/>
    </link>

    <joint name="${name}_ball_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_ball_link"/>
    </joint>

    <xacro:orbita2dof_control
      name="${name}"
      joint1="${joint1}" joint2="${joint2}"
      port_a="${port_a}" port_b="${port_b}" id_a="${id_a}" id_b="${id_b}" offset_a="${offset_a}" offset_b="${offset_b}" ratio_a="${ratio_a}" ratio_b="${ratio_b}"
    />

  </xacro:macro>
</robot>
