<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="smartgripper" params="prefix parent side damping friction gripper_port gripper_id">

  <xacro:include filename="$(find reachy_description)/ros2_control/smartgripper.ros2_control.xacro"/>

  <xacro:property name="gripper_length" value="0.12"/>
  <xacro:property name="gripper_radius" value="0.03"/>
  <xacro:property name="gripper_mass" value="0.25"/>

  <xacro:if value="${side == 'left'}">
    <xacro:property name="reflect" value="-1"/>
    <xacro:property name="min_grasping_finger" value="-2.094"/>
    <xacro:property name="max_grasping_finger" value="0.785"/>

  </xacro:if>
  <xacro:if value="${side == 'right'}">
    <xacro:property name="reflect" value="1"/>
    <xacro:property name="min_grasping_finger" value="-0.785"/>
    <xacro:property name="max_grasping_finger" value="2.094"/>

  </xacro:if>

  <xacro:property name="p" value="${prefix}_gripper"/>

  <link name="${p}_palm_link">
    <collision>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} ${gripper_radius*2} ${gripper_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} ${gripper_radius*2} ${gripper_length/2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <xacro:inertial_cuboid mass="${gripper_mass*0.85}" xyz="0 0 ${gripper_length/4}"  rpy="0 0 0" x_length="${gripper_radius}" y_length="${gripper_radius*2}" z_length="${gripper_length/2}"/>
  </link>

  <joint name="${p}_palm" type="fixed">
    <origin xyz="0 0 0" rpy="0.0 0 0.0"/>
    <parent link="${parent}"/>
    <child link="${p}_palm_link"/>
  </joint>

  <link name="${p}_index_link">
    <collision>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} 0.01 ${gripper_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} 0.01 ${gripper_length/2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <xacro:inertial_cuboid mass="${gripper_mass*0.1}" xyz="0 ${gripper_radius} ${gripper_length/4}"  rpy="0 0 0" x_length="${gripper_radius}" y_length="0.01" z_length="${gripper_length/2}"/>
  </link>


  <link name="${p}_index_mimic_link">
    <collision>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} 0.01 ${gripper_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${gripper_length/4} " rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_radius} 0.01 ${gripper_length/2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <xacro:inertial_cuboid mass="${gripper_mass*0.1}" xyz="0 ${gripper_radius} ${gripper_length/4}"  rpy="0 0 0" x_length="${gripper_radius}" y_length="0.01" z_length="${gripper_length/2}"/>
  </link>


  <joint name="${p}_finger" type="revolute">
    <origin xyz="0 ${reflect*gripper_radius} ${gripper_length/2}" rpy="0 0 0"/>
    <parent link="${p}_palm_link"/>
    <child link="${p}_index_link"/>
    <axis xyz="1 0 0"/>
    <limit lower="${min_grasping_finger}" upper="${max_grasping_finger}" effort="1000.0" velocity="0.0"/>
    <dynamics damping="${damping}" friction="${friction}"/>
  </joint>

 <joint name="${p}_finger_mimic" type="revolute">
    <origin xyz="0 ${-reflect*gripper_radius} ${gripper_length/2}" rpy="0 0 0"/>
    <parent link="${p}_palm_link"/>
    <child link="${p}_index_mimic_link"/>
    <axis xyz="1 0 0"/>
    <limit lower="${min_grasping_finger}" upper="${max_grasping_finger}" effort="1000.0" velocity="0.0"/>
    <dynamics damping="${damping}" friction="${friction}"/>
    <mimic joint="${p}_finger" multiplier="-1" offset="0" />
  </joint>


  <xacro:smart_gripper_control
    name="${p}"
    gripper_port="${gripper_port}"
    gripper_id="${gripper_id}"
    min_grasping_finger="${min_grasping_finger}"
    max_grasping_finger="${max_grasping_finger}"
  />

</xacro:macro>
</robot>
