controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    neck_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    # r_shoulder_forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    # r_elbow_forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    # r_wrist_forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    # l_shoulder_forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    # l_elbow_forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    # l_wrist_forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController


    r_arm_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    l_arm_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_current_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_mode_controller:
      type: forward_command_controller/ForwardCommandController

    antenna_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    antenna_current_controller:
      type: forward_command_controller/ForwardCommandController

    antenna_mode_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_limit_controller:
      type: forward_command_controller/ForwardCommandController

    forward_speed_limit_controller:
      type: forward_command_controller/ForwardCommandController

    forward_pid_controller:
      type: pid_command_controller/PIDCommandController

    tripod_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false


tripod_forward_position_controller:
  ros__parameters:
    joints:
      - back_bar_prism_joint
    interface_name: position
    use_sim_time: false


neck_forward_position_controller:
  ros__parameters:
    joints:
      - neck_roll
      - neck_pitch
      - neck_yaw
    interface_name: position
    use_sim_time: false


# r_shoulder_forward_position_controller:
#   ros__parameters:
#     joints:
#       - r_shoulder_roll
#       - r_shoulder_pitch
#     interface_name: position
#     use_sim_time: false

# r_elbow_forward_position_controller:
#   ros__parameters:
#     joints:
#       - r_elbow_yaw
#       - r_elbow_pitch
#     interface_name: position
#     use_sim_time: false

# r_wrist_forward_position_controller:
#   ros__parameters:
#     joints:
#       - r_wrist_roll
#       - r_wrist_pitch
#       - r_wrist_yaw
#     interface_name: position
#     use_sim_time: false

# l_shoulder_forward_position_controller:
#   ros__parameters:
#     joints:
#       - l_shoulder_roll
#       - l_shoulder_pitch
#     interface_name: position
#     use_sim_time: false

# l_elbow_forward_position_controller:
#   ros__parameters:
#     joints:
#       - l_elbow_yaw
#       - l_elbow_pitch
#     interface_name: position
#     use_sim_time: false

# l_wrist_forward_position_controller:
#   ros__parameters:
#     joints:
#       - l_wrist_roll
#       - l_wrist_pitch
#       - l_wrist_yaw
#     interface_name: position
#     use_sim_time: false
r_arm_forward_position_controller:
  ros__parameters:
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_elbow_yaw
      - r_elbow_pitch
      - r_wrist_roll
      - r_wrist_pitch
      - r_wrist_yaw
    interface_name: position
    use_sim_time: false


l_arm_forward_position_controller:
  ros__parameters:
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_elbow_yaw
      - l_elbow_pitch
      - l_wrist_roll
      - l_wrist_pitch
      - l_wrist_yaw
    interface_name: position
    use_sim_time: false

antenna_forward_position_controller:
  ros__parameters:
    joints:
      - antenna_left
      - antenna_right
    interface_name: position
    use_sim_time: false


gripper_forward_position_controller:
  ros__parameters:
    joints:
      - r_hand_finger
      - l_hand_finger
    interface_name: position
    use_sim_time: false

gripper_current_controller:
  ros__parameters:
    joints:
      - r_hand_raw_motor_1
      - l_hand_raw_motor_1
    interface_name: current
    use_sim_time: false


antenna_current_controller:
  ros__parameters:
    joints:
      - antenna_left_raw_motor
      - antenna_right_raw_motor
    interface_name: current
    use_sim_time: false

antenna_mode_controller:
  ros__parameters:
    joints:
      - antenna_left_raw_motor
      - antenna_right_raw_motor
    interface_name: mode
    use_sim_time: false


gripper_mode_controller:
  ros__parameters:
    joints:
      - l_hand_raw_motor_1
      - r_hand_raw_motor_1
    interface_name: mode
    use_sim_time: false


forward_torque_controller:
  ros__parameters:
    joints:
      - neck
      - r_shoulder
      - r_elbow
      - r_wrist
      - r_hand
      - l_shoulder
      - l_elbow
      - l_wrist
      - l_hand
      - antenna_left
      - antenna_right
    interface_name: torque
    use_sim_time: false

forward_torque_limit_controller:
  ros__parameters:
    joints:
      - neck_raw_motor_1
      - neck_raw_motor_2
      - neck_raw_motor_3
      - r_shoulder_raw_motor_1
      - r_shoulder_raw_motor_2
      - r_elbow_raw_motor_1
      - r_elbow_raw_motor_2
      - r_wrist_raw_motor_1
      - r_wrist_raw_motor_2
      - r_wrist_raw_motor_3
      - r_hand_raw_motor_1
      - l_shoulder_raw_motor_1
      - l_shoulder_raw_motor_2
      - l_elbow_raw_motor_1
      - l_elbow_raw_motor_2
      - l_wrist_raw_motor_1
      - l_wrist_raw_motor_2
      - l_wrist_raw_motor_3
      - l_hand_raw_motor_1
      - antenna_left_raw_motor
      - antenna_right_raw_motor
    interface_name: torque_limit
    use_sim_time: false

forward_speed_limit_controller:
  ros__parameters:
    joints:
      - neck_raw_motor_1
      - neck_raw_motor_2
      - neck_raw_motor_3
      - r_shoulder_raw_motor_1
      - r_shoulder_raw_motor_2
      - r_elbow_raw_motor_1
      - r_elbow_raw_motor_2
      - r_wrist_raw_motor_1
      - r_wrist_raw_motor_2
      - r_wrist_raw_motor_3
      - r_hand_raw_motor_1
      - l_shoulder_raw_motor_1
      - l_shoulder_raw_motor_2
      - l_elbow_raw_motor_1
      - l_elbow_raw_motor_2
      - l_wrist_raw_motor_1
      - l_wrist_raw_motor_2
      - l_wrist_raw_motor_3
      - l_hand_raw_motor_1
      - antenna_left_raw_motor
      - antenna_right_raw_motor
    interface_name: speed_limit
    use_sim_time: false


forward_pid_controller:
  ros__parameters:
    joints:
      - neck_raw_motor_1
      - neck_raw_motor_2
      - neck_raw_motor_3
      - r_shoulder_raw_motor_1
      - r_shoulder_raw_motor_2
      - r_elbow_raw_motor_1
      - r_elbow_raw_motor_2
      - r_wrist_raw_motor_1
      - r_wrist_raw_motor_2
      - r_wrist_raw_motor_3
      - r_hand_raw_motor_1
      - l_shoulder_raw_motor_1
      - l_shoulder_raw_motor_2
      - l_elbow_raw_motor_1
      - l_elbow_raw_motor_2
      - l_wrist_raw_motor_1
      - l_wrist_raw_motor_2
      - l_wrist_raw_motor_3
      - l_hand_raw_motor_1
      - antenna_left_raw_motor
      - antenna_right_raw_motor
    use_sim_time: false
