controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    neck_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    r_arm_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    l_arm_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_limit_controller:
      type: forward_command_controller/ForwardCommandController

    forward_speed_limit_controller:
      type: forward_command_controller/ForwardCommandController

    forward_pid_controller:
      type: pid_command_controller/PIDCommandController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false

neck_forward_position_controller:
  ros__parameters:
    joints:
      - neck_roll
      - neck_pitch
      - neck_yaw
    interface_name: position
    use_sim_time: false

r_arm_forward_position_controller:
  ros__parameters:
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_elbow_yaw
      - r_elbow_pitch
      - r_wrist_roll
      - r_wrist_pitch
      - r_wrist_yaw
    interface_name: position
    use_sim_time: false


l_arm_forward_position_controller:
  ros__parameters:
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_elbow_yaw
      - l_elbow_pitch
      - l_wrist_roll
      - l_wrist_pitch
      - l_wrist_yaw
    interface_name: position
    use_sim_time: false


gripper_forward_position_controller:
  ros__parameters:
    joints:
      - r_gripper_finger
      - l_gripper_finger
    interface_name: position
    use_sim_time: false

forward_torque_controller:
  ros__parameters:
    joints:
      - neck
      - r_shoulder
      - r_elbow
      - r_wrist
      - r_gripper_finger
      - l_shoulder
      - l_elbow
      - l_wrist
      - l_gripper_finger

    interface_name: torque
    use_sim_time: false

forward_torque_limit_controller:
  ros__parameters:
    joints:
      - neck_raw_motor_1
      - neck_raw_motor_2
      - neck_raw_motor_3
      - r_shoulder_raw_motor_1
      - r_shoulder_raw_motor_2
      - r_elbow_raw_motor_1
      - r_elbow_raw_motor_2
      - r_wrist_raw_motor_1
      - r_wrist_raw_motor_2
      - r_wrist_raw_motor_3
      - r_gripper_finger
      - l_shoulder_raw_motor_1
      - l_shoulder_raw_motor_2
      - l_elbow_raw_motor_1
      - l_elbow_raw_motor_2
      - l_wrist_raw_motor_1
      - l_wrist_raw_motor_2
      - l_wrist_raw_motor_3
      - l_gripper_finger

    interface_name: torque_limit
    use_sim_time: false

forward_speed_limit_controller:
  ros__parameters:
    joints:
      - neck_raw_motor_1
      - neck_raw_motor_2
      - neck_raw_motor_3
      - r_shoulder_raw_motor_1
      - r_shoulder_raw_motor_2
      - r_elbow_raw_motor_1
      - r_elbow_raw_motor_2
      - r_wrist_raw_motor_1
      - r_wrist_raw_motor_2
      - r_wrist_raw_motor_3
      - r_gripper_finger
      - l_shoulder_raw_motor_1
      - l_shoulder_raw_motor_2
      - l_elbow_raw_motor_1
      - l_elbow_raw_motor_2
      - l_wrist_raw_motor_1
      - l_wrist_raw_motor_2
      - l_wrist_raw_motor_3
      - l_gripper_finger

    interface_name: speed_limit
    use_sim_time: false


forward_pid_controller:
  ros__parameters:
    joints:
      - neck_raw_motor_1
      - neck_raw_motor_2
      - neck_raw_motor_3
      - r_shoulder_raw_motor_1
      - r_shoulder_raw_motor_2
      - r_elbow_raw_motor_1
      - r_elbow_raw_motor_2
      - r_wrist_raw_motor_1
      - r_wrist_raw_motor_2
      - r_wrist_raw_motor_3
      - r_gripper_finger
      - l_shoulder_raw_motor_1
      - l_shoulder_raw_motor_2
      - l_elbow_raw_motor_1
      - l_elbow_raw_motor_2
      - l_wrist_raw_motor_1
      - l_wrist_raw_motor_2
      - l_wrist_raw_motor_3
      - l_gripper_finger

    use_sim_time: false
