# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 0.0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  l_elbow_pitch:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  l_elbow_yaw:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  l_gripper_finger:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  l_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  l_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  l_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  l_wrist_roll:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  l_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  neck_pitch:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  neck_roll:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  neck_yaw:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  r_elbow_pitch:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  r_elbow_yaw:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  r_gripper_finger:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  r_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  r_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  r_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  r_wrist_roll:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
  r_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 500.0
    has_acceleration_limits: true
    max_acceleration: 100.0
